(ns angular-phonecat-re-frame.core
  (:require
    [reagent.core :as reagent :refer [atom]]
    [reagent.session :as session]
    [reitit.frontend :as reitit]
    [clerk.core :as clerk]
    [accountant.core :as accountant]
    [re-frame.core :as re-frame]))

;; Routes

(def router
  (reitit/router
    [["/" :index]
     ["/items"
      ["" :items]
      ["/:item-id" :item]]
     ["/about" :about]]))

(defn path-for [route & [params]]
  (if params
    (:path (reitit/match-by-name router route params))
    (:path (reitit/match-by-name router route))))

(path-for :about)

;; Handlers

(re-frame/reg-event-db
  :initialise-db
  (fn [_ _]
    {:phones [{:name "Nexus S" :snippet "Fast just got faster with Nexus S."}
              {:name "Motorola XOOM™ with Wi-Fi" :snippet "The Next, Next Generation tablet."}
              {:name "Motoral Xoom" :snippet "The Next, Next Generation tablet."}]}))

;; Page components

(defn home-page []
  (fn []
    [:ul
     [:li
      [:span "Nexus S"]
      [:p "Fast just got faster with Nexus S."]]
     [:li
      [:span "Motorola XOOM with Wi-Fi"]
      [:p "The Next, Next Generation tablet."]]]))

(defn items-page []
  (fn []
    [:span.main
     [:h1 "The items of angular-phonecat-re-frame"]
     [:ul (map (fn [item-id]
                 [:li {:name (str "item-" item-id) :key (str "item-" item-id)}
                  [:a {:href (path-for :item {:item-id item-id})} "Item: " item-id]])
               (range 1 60))]]))

(defn item-page []
  (fn []
    (let [routing-data (session/get :route)
          item (get-in routing-data [:route-params :item-id])]
      [:span.main
       [:h1 (str "Item " item " of angular-phonecat-re-frame")]
       [:p [:a {:href (path-for :items)} "Back to the list of items"]]])))

(defn about-page []
  (fn [] [:span.main
          [:h1 "About angular-phonecat-re-frame"]]))

;; Translate routes -> page components

(defn page-for [route]
  (case route
    :index #'home-page
    :about #'about-page
    :items #'items-page
    :item #'item-page))

;; Page mounting component

(defn current-page []
  (fn []
    (let [page (:current-page (session/get :route))]
      [:div
       [:header
        [:p [:a {:href (path-for :index)} "Home"] " | "
         [:a {:href (path-for :about)} "About angular-phonecat-re-frame"]]]
       [page]
       [:footer
        [:p "angular-phonecat-re-frame was generated by the "
         [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]]])))

;; Initialize app

(defn mount-root []
  (re-frame/dispatch [:initialise-db])
  (reagent/render [current-page] (.getElementById js/document "app")))

(defn init! []
  (clerk/initialize!)
  (accountant/configure-navigation!
    {:nav-handler
     (fn [path]
       (let [match (reitit/match-by-path router path)
             current-page (:name (:data match))
             route-params (:path-params match)]
         (reagent/after-render clerk/after-render!)
         (session/put! :route {:current-page (page-for current-page)
                               :route-params route-params})
         (clerk/navigate-page! path)
         ))
     :path-exists?
     (fn [path]
       (boolean (reitit/match-by-path router path)))})
  (accountant/dispatch-current!)
  (mount-root))
